apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: [YOUR REGISTRY]/echoserver:latest
        env:
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: pod
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: node
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /healthcheck
            scheme: HTTP
            port: http
        livenessProbe:
          httpGet:
            path: /healthcheck
            scheme: HTTP
            port: http
