apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS","http":"HTTP"}'
  name: echo
  labels:
    app: echo
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: http
  - port: 443
    protocol: TCP
    name: https
    targetPort: https
  selector:
    app: echo
